### ISSUE TITLE
[Question] reusing this library to measure size of clipping caps on Threejs

### ISSUE THREAD

**Issue by PlopTheReal** [daign/gaps.js#1]
Hey,
I was wondering if that library could be reused or transformed in some way to compute the size of Threejs geometries, particularly caps on clipped meshes. 
This demo shows LineSegments created on the caps : https://gkjohnson.github.io/three-mesh-bvh/example/bundle/clippedEdges.html
I was wondering if we could measure the geometries created then.
For instance measuring automatically the distances between the two dots here: 
![image](https://user-images.githubusercontent.com/58116071/171383109-dd6c12f8-3bcf-4725-a023-42aaacc6fda3.png)

But also the other distances within the geomtry.

**Comment by daign** [comment]
You would have to make sure that all edges are orthogonal, because the algorithm here was only created for rectangles.
